linters-settings:
  varnamelen:
    min-name-length: 2
    max-distance: 20
  nlreturn:
    # Size of the block (including return statement that is still "OK")
    # so no return split required.
    # Default: 1
    block-size: 3
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: goCamel

linters:
  enable-all: true
  disable:
    # - godox
    - dupword
    - depguard
    - mnd
    - exhaustruct
    - funlen
    - tenv
    - varnamelen
